<a href="https://colab.research.google.com/github/azhargies/ML-Projects/blob/CV/Diabetes_prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from tensorflow import keras
from tensorflow.keras import Sequential

In [39]:
data = pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [40]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [41]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [42]:
X = data.drop(["Outcome"], axis = 1)
Y = data["Outcome"]

In [43]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [44]:
Y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_scaled = sc.fit_transform(X)

In [46]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x_scaled, Y, test_size = 0.2, random_state = 42)

In [47]:
x_scaled[:2]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191]])

In [ ]:
model = Sequential(
    [keras.layers.Dense(units = 1, input_shape = (8,), activation = "sigmoid")]
)

model.summary()

model.compile(keras.optimizers.Adam(
    learning_rate=0.01), loss = "binary_crossentropy", metrics = ["accuracy"])

model.fit(xtrain, ytrain, epochs = 1000)

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 1)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.7517 - accuracy: 0.5749
Epoch 2/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.6366 - accuracy: 0.6596
Epoch 3/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.5739 - accuracy: 0.7150
Epoch 4/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.5383 - accuracy: 0.7459
Epoch 5/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.5177 - accuracy: 0.7508
Epoch 6/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.5037 - accur

In [49]:
model_new = Sequential()

model_new.add(keras.layers.Dense(128, input_shape = (8,), activation = "relu"))
model_new.add(keras.layers.Dropout(0.2))
model_new.add(keras.layers.Dense(128, input_shape = (8,), activation = "relu"))
model_new.add(keras.layers.Dropout(0.2))
model_new.add(keras.layers.Dense(units = 1, activation = "sigmoid"))

model_new.summary()

model_new.compile(keras.optimizers.Adam(
    learning_rate=0.01), loss = "binary_crossentropy", metrics = ["accuracy"])

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_21 (Dense)            (None, 128)               1152      
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_22 (Dense)            (None, 128)               16512     
                                                                 
 dropout_3 (Dropout)         (None, 128)               0         
                                                                 
 dense_23 (Dense)            (None, 1)                 129       
                                                                 
Total params: 17,793
Trainable params: 17,793
Non-trainable params: 0
_________________________________________________________________


In [50]:
model_new.fit(xtrain, ytrain, epochs = 1000)

Epoch 1/1000
20/20 [==============================] - 1s 3ms/step - loss: 0.5400 - accuracy: 0.7329
Epoch 2/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.4757 - accuracy: 0.7736
Epoch 3/1000
20/20 [==============================] - 0s 4ms/step - loss: 0.4449 - accuracy: 0.7915
Epoch 4/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.4481 - accuracy: 0.7818
Epoch 5/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.4357 - accuracy: 0.7769
Epoch 6/1000
20/20 [==============================] - 0s 3ms/step - loss: 0.4357 - accuracy: 0.7899
Epoch 7/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.4199 - accuracy: 0.8013
Epoch 8/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.4156 - accuracy: 0.7899
Epoch 9/1000
20/20 [==============================] - 0s 3ms/step - loss: 0.4088 - accuracy: 0.8029
Epoch 10/1000
20/20 [==============================] - 0s 3ms/step - loss: 0.4169 - accuracy: 0.7948

In [51]:
model_new.evaluate(xtest,ytest)

5/5 [==============================] - 0s 3ms/step - loss: 4.6527 - accuracy: 0.6688


[4.6526899337768555, 0.6688311696052551]

In [64]:
xtest[11:15]

array([[ 0.93691372,  1.8185353 ,  1.338689  ,  0.65635768, -0.69289057,
         0.28016432, -0.92982297,  2.27687294],
       [ 0.04601433,  0.84832379, -0.47073225,  0.40544544,  2.06827033,
        -0.13866919, -0.97210463, -0.36084741],
       [ 0.3429808 , -0.77912776,  0.25303625, -0.15910711, -0.11113655,
         0.20401277,  1.58593589,  0.83038113],
       [-0.54791859, -1.02950492, -0.57412775,  0.34271738, -0.55396424,
        -0.4559673 ,  0.88828847, -0.95646168]])

In [67]:
ytest[11:20]

212    0
199    1
265    0
760    0
356    1
501    0
457    0
604    1
213    1
Name: Outcome, dtype: int64

In [68]:
model_new.predict(xtest[11:20])

1/1 [==============================] - 0s 22ms/step


array([[9.9999988e-01],
       [5.8216737e-10],
       [9.9917722e-01],
       [5.5665635e-11],
       [4.7703076e-14],
       [1.0683725e-13],
       [1.9714047e-13],
       [9.9989033e-01],
       [9.9999940e-01]], dtype=float32)